name: Update Template Files
on:
  workflow_dispatch:
    inputs:
      skip_pattern:
        description: 'Regex pattern to skip files (e.g.: ".*\.md$")'
        required: false
        default: ''

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone template repo
        run: |
          REPO_URL=$(jq -r '.src' .github/settings/repo-config.json)
          git clone "$REPO_URL" template-repo --depth 1

      - name: Copy relevant files
        run: |
          # Copy .github directory excluding settings
          rsync -av --delete template-repo/.github/ .github/ --exclude=settings
          
          # Clean up template files
          rm -rf template-repo

          # Restore skipped files if pattern provided
          if [ -n "${{ inputs.skip_pattern }}" ]; then
            git restore $(git ls-files | grep -E "${{ inputs.skip_pattern }}")
          fi

      - name: Commit and push changes
        run: |
          git add .
          if ! git diff --quiet; then
            git commit -m "chore: Update template files$([ "${{ inputs.skip_pattern }}" ] && echo " (skipped ${{ inputs.skip_pattern }})")"
            git push
          else
            echo "No changes to commit"
          fi
